### ISSUE TITLE
Add Support for PostgreSQL Schemas

### ISSUE THREAD

**Issue by bstoots** [IntegralSoftware/flysystem-pdo-adapter#1]
The tableName regex is a bit too strict to allow Postgres schema names, e.g. someschema.files.  Adding period to the regex check should be sufficient to make this work.

**Comment by zaak** [comment]
Done in https://github.com/IntegralSoftware/flysystem-pdo-adapter/commit/c0f6843ce8c7a1b4450b43744963d23da92f3087.
