### ISSUE TITLE
Support for Flysystem version 2.x

### ISSUE THREAD

**Issue by aedart** [IntegralSoftware/flysystem-pdo-adapter#13]
Will there be support for [Flysystem version 2](https://flysystem.thephpleague.com/v2/docs/)? If so, would you be able to tell when you plan do release a new version? - Your best guess will suffice...

**Comment by holtkamp** [comment]
Had a look at this and it seems quite some work to realise it since quite some things have changed. 

Instead of extending the AbstractAdapter, the https://github.com/thephpleague/flysystem/blob/3.x/src/FilesystemAdapter.php needs to be implemented.

**Comment by aedart** [comment]
Hi @holtkamp 
Since I made this request, I have moved on to creating my own version. Its not something that I initially wanted, but my projected required the latest version of flysystem.
You can take a look at it, at: https://aedart.github.io/athenaeum/archive/current/flysystem/
