### ISSUE TITLE
Create table automatically

### ISSUE THREAD

**Issue by holtkamp** [IntegralSoftware/flysystem-pdo-adapter#7]
Nice adapter thanks!

Would it be an idea to have a default database table created automatically after detecting the used database engine?

For example for MySQL:

```SQL
CREATE TABLE IF NOT EXISTS files (
  id int(11) NOT NULL AUTO_INCREMENT,
  path varchar(255) NOT NULL,
  type enum('file','dir') NOT NULL,
  contents longblob,
  size int(11) NOT NULL DEFAULT 0,
  mimetype varchar(127),
  timestamp int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY path_unique (path)
);
```

This would only create the table when required.

**Comment by zaak** [comment]
Interesting idea, but I think this would make the adapter kinda bloated -  each time the adapter is instantiated you would need to check what DBMS you're talking to and execute `CREATE TABLE ...` if required, which means more unnecessary queries. For now it's DBMS agnostic and only `PDO` layer is used.

**Comment by holtkamp** [comment]
True, thanks for the swift response!
