### ISSUE TITLE
Register as "official" FlySystem adapter 

### ISSUE THREAD

**Issue by holtkamp** [IntegralSoftware/flysystem-pdo-adapter#8]
Before working with this adapter, I tried the [PHP Content Repository Adapter](https://flysystem.thephpleague.com/docs/adapter/phpcr/) to be able to store content in a database. This adapter works well, only it does not perform very well when a lot of records are involved (~100k records), so I looked for a simpler approach.

The PDO Adapter is very "to-the-point" and efficient and performs great. During synchronization of content in a MySQL database to local file system we reach rates of up to 60 records/files per second.

Maybe it is an idea to register the PDO Adapter at https://flysystem.thephpleague.com? If it was listed there I probably never had tried the PHP Content Repository adapter and used the PDO Adapter directly!

Also see http://flysystem.thephpleague.com/docs/advanced/creating-an-adapter/#sharing-the-wealth

**Comment by zaak** [comment]
Hi @holtkamp! Thanks for the feedback. TBH I have some doubts if this adapter should be shown to a wider public, as storing files in database is generally considered a bad practice. On the other hand, I saw a few projects where it was a requirement, which was also the reason why this adapter was created.

@frankdejonge What do you think about this idea?

**Comment by frankdejonge** [comment]
@zaak Hi! If you're willing to keep maintaining the adapter we can publish this under the league flag. Let me know and I'll follow up on what that would entail.

**Comment by zaak** [comment]
@frankdejonge: Cool then. Just sent a PR which adds a link to readme https://github.com/thephpleague/flysystem/pull/945.

**Comment by holtkamp** [comment]
Nicely!
